#!/bin/bash

# Change this if your project is not named opendatahub
export TEST_NAMESPACE=${TEST_NAMESPACE:-"test-harness"}

millisecond=1
second=$(( 1000 * millisecond ))
minute=$(( 60 * second ))
fiveminute=$(( 300 * second ))
defaulttimeout=$(( 1200 * second ))
defaultinterval=$(( 10 ))

function header() {
    os::text::print_blue $1
}
